apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokemon-cards
  labels:
    app.kubernetes.io/name: pokemon-cards
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: pokemon.sent-tech.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pokemon-cards
                port:
                  name: http
  tls:
    - hosts:
        - pokemon.sent-tech.ca
      secretName: pokemon-cards-tls
