apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pokemon-cards
  labels:
    app.kubernetes.io/name: pokemon-cards
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pokemon-cards
      app.kubernetes.io/component: web
