apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod
patches:
  - target:
      kind: PodDisruptionBudget
      name: pokemon-cards
    patch: |-
      $patch: delete
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: pokemon-cards
